// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBookshelfWeb.DataAccess.Data;

#nullable disable

namespace TheBookshelf.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.7.23375.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheBookshelf.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("TheBookshelf.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Stephen King",
                            CategoryId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis faucibus accumsan nulla, non ultrices sem. Donec at felis ut turpis condimentum elementum.",
                            ISBN = "9788556511928",
                            ImageUrl = "",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 21.0,
                            Price50 = 24.0,
                            Title = "Holly"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Robert Jordan",
                            CategoryId = 4,
                            Description = "Suspendisse eu magna vitae ex consequat placerat. Morbi vel pretium nunc, in imperdiet dui...",
                            ISBN = "0812511816",
                            ImageUrl = "",
                            ListPrice = 8.0,
                            Price = 7.0,
                            Price100 = 5.5,
                            Price50 = 6.0,
                            Title = "The Eye of the World"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George R. R. Martin",
                            CategoryId = 4,
                            Description = "Donec eu dapibus arcu. Praesent egestas, sem sed auctor malesuada, sapien ligula dignissim urna, sed feugiat ante massa id nisl.",
                            ISBN = "0553808044",
                            ImageUrl = "",
                            ListPrice = 35.0,
                            Price = 32.0,
                            Price100 = 25.0,
                            Price50 = 28.0,
                            Title = "A Game of Thrones: The Illustrated Edition: A Song of Ice and Fire: Book One"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Stephen King",
                            CategoryId = 4,
                            Description = "Fusce accumsan orci diam, sed commodo massa gravida id. Nunc ut ante cursus, scelerisque nisl sit amet, ornare eros.",
                            ISBN = "9781668002179",
                            ImageUrl = "",
                            ListPrice = 17.0,
                            Price = 15.0,
                            Price100 = 12.0,
                            Price50 = 14.0,
                            Title = "Fairy Tale"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Hannah Nicole Maehrer",
                            CategoryId = 6,
                            Description = "Ut mattis placerat odio, et lobortis ipsum volutpat ut. Nullam laoreet metus eu urna pellentesque auctor. Pellentesque et diam nec nisl dictum tincidunt.",
                            ISBN = "9788556511928",
                            ImageUrl = "",
                            ListPrice = 17.0,
                            Price = 16.0,
                            Price100 = 11.0,
                            Price50 = 14.0,
                            Title = "Assistant to the Villian"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Sarah J. Maas",
                            CategoryId = 4,
                            Description = "Sed maximus purus eget libero placerat, accumsan viverra nisl pulvinar. Ut arcu nulla, feugiat at metus vel, volutpat iaculis quam.",
                            ISBN = "9781639732869",
                            ImageUrl = "",
                            ListPrice = 29.0,
                            Price = 27.0,
                            Price100 = 22.0,
                            Price50 = 25.0,
                            Title = "House of Flame and Shadow"
                        },
                        new
                        {
                            Id = 7,
                            Author = "William Kent Krueger",
                            CategoryId = 7,
                            Description = "Donec ipsum mauris, rutrum ut arcu in, imperdiet euismod orci. Fusce et odio quis tellus feugiat luctus.",
                            ISBN = "9781668047903",
                            ImageUrl = "",
                            ListPrice = 21.0,
                            Price = 20.0,
                            Price100 = 17.0,
                            Price50 = 18.0,
                            Title = "The River We Remember"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Harper Lee",
                            CategoryId = 8,
                            Description = "Curabitur sodales sodales lectus, vel feugiat arcu aliquam eget. Pellentesque eu turpis eu nunc aliquam dignissim.",
                            ISBN = "0446310786",
                            ImageUrl = "",
                            ListPrice = 13.0,
                            Price = 11.0,
                            Price100 = 9.0,
                            Price50 = 10.0,
                            Title = "To Kill a Mockingbird"
                        });
                });

            modelBuilder.Entity("TheBookshelf.Models.Product", b =>
                {
                    b.HasOne("TheBookshelf.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
